import sys


def exit_with_error():
    sys.exit(1)
